config/routes.rb
Rails.application.routes.draw do
  # Aqui le estoy diciendo a rails que cuando accedan a la direccion /carrito, los redirija 
  # a la accion carrito del controlador de payments
  get "/carrito", to: "payments#carrito"
  get "/compras", to: "payments#compras"
  # es muy importante que esta ruta este arriba de resources payments
  get "payments/express"
  get "transactions/checkout"
  resources :attachments
  resources :posts
  resources :payments
  # Lo de controllers, es para que reciba los hash que devuelve omniauth para ver si se realizo el
  # Inicio de sesion desde facebook o twitter por ejemplo
  devise_for :usuarios, controllers: {omniauth_callbacks: "omniauth_callbacks",
  									 registrations: "registrations"}
  
  # Para manejar manualmente algunos eventos del usuario con el controlador
  # como por ejemplo crear una vista para ver el perfil
  resources :usuario 
  
  

  get 'welcome/index'
  post "usuario/follow"
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_header.html.erb
<header>
  <nav>
    <ul class="nav nav-tabs">
      <li>
        <%= link_to "Inicio", root_path %>
      </li>
      <li>
        <%= link_to "Posts", posts_path %>
      </li>
      <% if usuario_signed_in? %>
        <li>
          <%= link_to "Mi carrito", carrito_path %>
        </li>
        <li>
          <%= link_to "Mis compras", compras_path %>
        </li>
        <li>
          <%= link_to "Editar perfil", edit_usuario_registration_path(current_usuario) %>
        </li>
        <li>
          <%= link_to "Mi perfil", current_usuario %>
        </li>
        <li>
          <%= link_to "Cerrar sesion", destroy_usuario_session_path, method: :delete %>
        </li>
      <%else%>
        <li>
          <%= link_to "Ingresar", new_usuario_session_path %>
        </li>
        <li>
          <%= link_to "Registrarse", new_usuario_registration_path %>
        </li>
      <%end%>
    </ul>
  </nav>
</header>