config/routes.rb
Rails.application.routes.draw do
  # Aqui le estoy diciendo a rails que cuando accedan a la direccion /carrito, los redirija 
  # a la accion carrito del controlador de payments
  get "/carrito", to: "payments#carrito"
  get "/compras", to: "payments#compras"
  # es muy importante que esta ruta este arriba de resources payments
  get "payments/express"
  get "transactions/checkout"
  resources :attachments
  resources :posts
  resources :payments
  # Lo de controllers, es para que reciba los hash que devuelve omniauth para ver si se realizo el
  # Inicio de sesion desde facebook o twitter por ejemplo
  devise_for :usuarios, controllers: {omniauth_callbacks: "omniauth_callbacks",
  									 registrations: "registrations"}
  
  # Para manejar manualmente algunos eventos del usuario con el controlador
  # como por ejemplo crear una vista para ver el perfil
  resources :usuario 
  
  

  get 'welcome/index'
  post "usuario/follow"
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :post
  # Llamo al concern para que haga la logica de guardar la imagen.
  include Picturable
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :set_attachment, only: [:show, :edit, :update, :destroy]

  # GET /attachments
  # GET /attachments.json
  def index
    @attachments = Attachment.all
  end

  # GET /attachments/1
  # GET /attachments/1.json
  def show
  end

  # GET /attachments/new
  def new
    @attachment = Attachment.new
  end

  # GET /attachments/1/edit
  def edit
  end

  # POST /attachments
  # POST /attachments.json
  def create
    @attachment = Attachment.new(attachment_params)

    respond_to do |format|
      if @attachment.save
        format.html { redirect_to @attachment, notice: 'Attachment was successfully created.' }
        format.json { render :show, status: :created, location: @attachment }
      else
        format.html { render :new }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attachments/1
  # PATCH/PUT /attachments/1.json
  def update
    respond_to do |format|
      if @attachment.update(attachment_params)
        format.html { redirect_to @attachment, notice: 'Attachment was successfully updated.' }
        format.json { render :show, status: :ok, location: @attachment }
      else
        format.html { render :edit }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attachments/1
  # DELETE /attachments/1.json
  def destroy
    @attachment.destroy
    respond_to do |format|
      format.html { redirect_to attachments_url, notice: 'Attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attachment
      @attachment = Attachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attachment_params
      params.require(:attachment).permit(:nombre, :extension, :post_id, :archivo)
    end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/views/attachments/_form.html.erb
<%= form_with(model: attachment, local: true) do |form| %>
  <% if attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attachment.errors.count, "error") %> prohibited this attachment from being saved:</h2>

      <ul>
      <% attachment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :archivo %>
    <%= form.file_field :archivo %>
  </div>

  <div class="field">
    <%= form.label :post_id, "Post"%>
    <% # 1er parametro: a que post pertenece, 2do todos los post en el select, 3ro el value del select, 4to el label que saldra en el select %>
    <%= form.collection_select :post_id, Post.all, :id, :titulo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/attachments/edit.html.erb
<h1>Editing Attachment</h1>

<%= render 'form', attachment: @attachment %>

<%= link_to 'Show', @attachment %> |
<%= link_to 'Back', attachments_path %>

app/views/attachments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Attachments</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Extension</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attachments.each do |attachment| %>
      <tr>
        <td><%= attachment.nombre %></td>
        <td><%= attachment.extension %></td>
        <td><%= attachment.post %></td>
        <td><%= link_to 'Show', attachment %></td>
        <td><%= link_to 'Edit', edit_attachment_path(attachment) %></td>
        <td><%= link_to 'Destroy', attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attachment', new_attachment_path %>

app/views/attachments/new.html.erb
<h1>New Attachment</h1>

<%= render 'form', attachment: @attachment %>

<%= link_to 'Back', attachments_path %>

app/views/attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @attachment.nombre %>
</p>

<p>
  <strong>Extension:</strong>
  <%= @attachment.extension %>
</p>

<p>
  <strong>Post:</strong>
  <%= @attachment.post %>
</p>

<%= link_to 'Edit', edit_attachment_path(@attachment) %> |
<%= link_to 'Back', attachments_path %>