config/routes.rb
Rails.application.routes.draw do
  # Aqui le estoy diciendo a rails que cuando accedan a la direccion /carrito, los redirija 
  # a la accion carrito del controlador de payments
  get "/carrito", to: "payments#carrito"
  get "/compras", to: "payments#compras"
  # es muy importante que esta ruta este arriba de resources payments
  get "payments/express"
  get "transactions/checkout"
  resources :attachments
  resources :posts
  resources :payments
  # Lo de controllers, es para que reciba los hash que devuelve omniauth para ver si se realizo el
  # Inicio de sesion desde facebook o twitter por ejemplo
  devise_for :usuarios, controllers: {omniauth_callbacks: "omniauth_callbacks",
  									 registrations: "registrations"}
  
  # Para manejar manualmente algunos eventos del usuario con el controlador
  # como por ejemplo crear una vista para ver el perfil
  resources :usuario 
  
  

  get 'welcome/index'
  post "usuario/follow"
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :usuario, dependent: :destroy # Si se borra un usuario, se borraran sus posts
  has_many :attachments
  has_many :payments
  validates :titulo, presence: true, uniqueness: true
  before_save :valores_por_default
  # Para mas informacion sobre el metodo message, ver video extra por el min 35-36
  after_create {|post| post.message 'create'}

  # Llamo al concern para que haga la logica de guardar la imagen.
  include Picturable
  include PublicActivity::Model
  # Cada vez que alguien cree un post, lo actualice o lo borre. Se va a guardar en la tabla activitys
  # un registro a esa nueva actividad
  tracked owner: Proc.new{ |controller, model| controller.current_usuario }

  def valores_por_default
  	# al interponer el || le estoy diciendo rails que asigne 0 al costo, solo cuando el 
  	# usuario no lo especifique
  	self.costo ||= 0
  end

  def usuario_ha_pagado? usuario_id
    self.payments.where(estado: 2).size > 0
  end

  def message action
    msg = {
      resource: 'posts',
      action: action,
      id: self.id,
      obj: self,
      username: self.usuario.username.capitalize,
      user_id: self.usuario.id
    }

    $redis.publish 'rt-change', msg.to_json
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_usuario!, except: [:show, :index]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    # necesita el current_usuario para que se asigne el post al usuario que lo esta creando
    @post = current_usuario.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:titulo, :contenido, :archivo, :costo)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :titulo %>
    <%= form.text_field :titulo, id: :post_titulo, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :archivo%>
    <%= form.file_field :archivo, class:"form-control" %>
  </div>
  
  <div class="form-group">
    <%= form.label :costo %>
    <!-- el step es para que html5 permita los puntos en un campo numerico-->
    <%= form.number_field :costo, class:"form-control", step: "any" %>
  </div>

  <div class="form-group">
    <%= form.label :contenido %>
    <%= form.text_area :contenido, id: :post_contenido, class:"form-control"%>
  </div>
  
  <div class="actions">
    <%= form.submit "Subir post", class:"btn btn-success"%>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<ul class="list-group">
  <% @posts.each do |post| %>
    <li class="list-group-item">
      <%= link_to post.titulo, post %>
    </li>
  <% end %>
</ul>

<% if usuario_signed_in? %>
  <%= link_to 'Crear post', new_post_path, class:"btn btn-primary" %>
<% end %>

app/views/posts/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-5 center-block no-float">
			<h1>Nuevo Post</h1>
			<%= render 'form', post: @post %>
			<%= link_to 'Back', posts_path %>
		</div>
	</div>
</div>

app/views/posts/show.html.erb
<div class="jumbotron">
	<h1><%= @post.titulo %></h1>
	<div>
		<%= @post.contenido %>
	</div>
	<% if usuario_signed_in? %>
		<% if @post.usuario_ha_pagado? current_usuario.id %>
			<% @post.attachments.each do |attachment| %>
				<%= link_to attachment.titulo, attachment %>
			<% end %>
		<% else %>
			<%= render "payments/form", payment: Payment.new, post: @post %>
		<% end %>
	<% end %>
</div>

<div class="text-right">
	<% if @post.usuario and usuario_signed_in? and @post.usuario == current_usuario %>
		<%= link_to 'Editar', edit_post_path(@post) %> |
		<%= link_to 'Eliminar', @post, method: :delete, data: {confim: "Estas seguro de borrar el post ?"} %> |
	<%end%>
	<%= link_to 'Back', posts_path %>
</div>

	